include_recipe "../cookbooks/micro/default"
include_recipe "../cookbooks/rcs/default"
include_recipe "../cookbooks/rust/default"
include_recipe "../cookbooks/xonsh/default"
include_recipe "../cookbooks/git/default"
