include_recipe "../cookbooks/micro/default"
include_recipe "../cookbooks/rcs/default"
include_recipe "../cookbooks/rust/default"
include_recipe "../cookbooks/fish/default"
include_recipe "../cookbooks/tmux/default"
include_recipe "../cookbooks/vim/default"
include_recipe "../cookbooks/bat/default"
