set nocompatible
filetype off
set fileencoding=utf-8
set encoding=utf-8
scriptencoding=utf-8
language ja_JP.UTF-8

" status line
set showcmd
set laststatus=2
set cmdheight=2

" view
set showmatch
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set ambiwidth=double
set nu
let g:rainbow_active = 1
set statusline=%F%m%r%h%w%=\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%lL,%vC][%p%%]\ [LEN=%L]

" cursor
set backspace=indent,eol,start
set whichwrap=b,s,h,l,<,>,[,]
set sidescroll=1

" seaerch
set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch

" File
set hidden
set confirm
set autoread
set noswapfile

" bell
set visualbell t_vb=
set noerrorbells

" space
set expandtab
set tabstop=2
set shiftwidth=2

" general key map
imap <C-c> <esc>
noremap! <C-c> <esc>

" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'Vundle/Vundle.vim'
Plugin 'luochen1990/rainbow'
Plugin 'rust-lang/rust.vim'
Plugin 'preservim/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'ryanoasis/vim-devicons'
Plugin 'prabirshrestha/async.vim'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'prabirshrestha/asyncomplete-lsp.vim'
Plugin 'mattn/vim-lsp-settings'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'arcticicestudio/nord-vim'
call vundle#end()
filetype plugin indent on
syntax enable

" vim-markdown
set nofoldenable

" nerdtree
noremap <C-n> :NERDTreeToggle<CR>
let g:NERDTreeGitStatusUseNerdFonts = 1
let g:NERDTreeGitStatusShowClean = 1

" LSP
noremap <C-l>h :LspHover<CR>
noremap <C-l>d :LspDefinition<CR>
noremap <C-l>D :LspDeclaration<CR>
noremap <C-l>p :LspPeekDefinition<CR>
noremap <C-l>P :LspPeekDeclaration<CR>
noremap <C-l>r :LspReferences<CR>
noremap <C-l><C-n>d :LspNextDiagnostic<CR>
noremap <C-l><C-n>e :LspNextError<CR>
noremap <C-l><C-n>r :LspNextReference<CR>
noremap <C-l><C-n>w :LspNextWarning<CR>
noremap <C-l><C-p>d :LspPreviousDiagnostic<CR>
noremap <C-l><C-p>e :LspPreviousError<CR>
noremap <C-l><C-p>r :LspPrevioustReference<CR>
noremap <C-l><C-p>w :LspPreviousWarning<CR>
let g:lsp_log_file = ''

" clipboard
set clipboard=unnamedplus,unnamed

" mouse
set mouse=a

" color
try
  colorscheme nord
  set termguicolors
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum" " 文字色
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum" " 背景色
catch
endtry
