set nocompatible
filetype off
set fileencoding=utf-8
set encoding=utf-8
scriptencoding=utf-8
language ja_JP.UTF-8

" status line
set showcmd
set laststatus=2
set cmdheight=2

" view
set showmatch
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set ambiwidth=double
set nu
let g:rainbow_active = 1
set statusline=%F%m%r%h%w%=\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%lL,%vC][%p%%]\ [LEN=%L]

" cursor
set backspace=indent,eol,start
set whichwrap=b,s,h,l,<,>,[,]
set sidescroll=1

" seaerch
set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch

" File
set hidden
set confirm
set autoread
set noswapfile

" bell
set visualbell t_vb=
set noerrorbells

" space
set expandtab
set tabstop=2
set shiftwidth=2

" general key map
imap <C-c> <esc>
noremap! <C-c> <esc>

" Vundle
try
  call plug#begin('~/.vim/plugged')
  Plug 'luochen1990/rainbow'
  Plug 'rust-lang/rust.vim', { 'for': 'rs' }
  Plug 'preservim/nerdtree'
  Plug 'Xuyuanp/nerdtree-git-plugin'
  Plug 'ryanoasis/vim-devicons'
  Plug 'prabirshrestha/vim-lsp'
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-lsp.vim'
  Plug 'mattn/vim-lsp-settings'
  Plug 'editorconfig/editorconfig-vim'
  Plug 'plasticboy/vim-markdown', { 'for': 'md' }
  Plug 'arcticicestudio/nord-vim'
  Plug 'dag/vim-fish', { 'for': 'fish' }
  Plug 'hrsh7th/vim-vsnip'
  Plug 'hrsh7th/vim-vsnip-integ'
  call plug#end()
catch
  echoerr "no plugin loaded"
endtry
filetype plugin indent on
syntax enable

" vim-markdown
set nofoldenable

" nerdtree
noremap <C-n> :NERDTreeToggle<CR>
let g:NERDTreeGitStatusUseNerdFonts = 1
let g:NERDTreeGitStatusShowClean = 1

" LSP
noremap <C-l>h :LspHover<CR>
noremap <C-l>d :LspDefinition<CR>
noremap <C-l>D :LspDeclaration<CR>
noremap <C-l>p :LspPeekDefinition<CR>
noremap <C-l>P :LspPeekDeclaration<CR>
noremap <C-l>r :LspReferences<CR>
noremap <C-l><C-d> :LspDocumentDiagnostics<CR>
noremap <C-l><C-n>d :LspNextDiagnostic<CR>
noremap <C-l><C-n>e :LspNextError<CR>
noremap <C-l><C-n>r :LspNextReference<CR>
noremap <C-l><C-n>w :LspNextWarning<CR>
noremap <C-l><C-p>d :LspPreviousDiagnostic<CR>
noremap <C-l><C-p>e :LspPreviousError<CR>
noremap <C-l><C-p>r :LspPrevioustReference<CR>
noremap <C-l><C-p>w :LspPreviousWarning<CR>

let g:WebDevIconsNerdTreeBeforeGlyphPadding = ""
let g:WebDevIconsUnicodeDecorateFolderNodes = v:true
if exists('g:loaded_webdevicons')
  call webdevicons#refresh()
endif

" clipboard
set clipboard=unnamedplus,unnamed

" mouse
set mouse=a

" color
try
  colorscheme nord
  set termguicolors
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum" " 文字色
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum" " 背景色
catch
endtry

